  name: Jekyll site CI

  on:
    push:
      branches: [ "Main" ]
    pull_request:
      branches: [ "Main" ]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Render Deployment
        uses: sws2apps/render-deployment@v1.2.0
        with:    
          serviceId: srv-ci4c4515rnupbo2toalg?key=bINER0rXEHs
          apiKey: rnd_F4NURipzT2rZleUVWzMHpyfJec9i
