  name: Jekyll site CI

  on:
    push:
      branches: [ "Main" ]
    pull_request:
      branches: [ "Main" ]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Render Deployment
        uses: sws2apps/render-deployment@v1.2.0
        with:    
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
